project:
  type: website
  output-dir: docs


website:
  title: "Matthew Roco-Calvo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Resume.qmd
      - Projects.qmd

format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    page-layout: full

editor: visual

