---
title: "Miscellaneous"
format: html
execute:
  message: false # use this to make sure messages don't show up
  warning: false
---

## Music

I love music, and I really enjoy singing. Unfortunately I am too scared to include videos of that, although I did actually consider it! I have decided to substitute it with some playlists I have made, I hope whoever is viewing this is not too dissapointed by this repacement. 

Anyway, here is a playlist I made for cloudier days, such as the one's we have been having here in Santa Barbara recently:

<iframe style="border-radius:12px" src="https://open.spotify.com/embed/playlist/4VpBOdDg8YRbLncDA1RGHB?utm_source=generator&theme=0" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>

Here is another playlist I have for sunnier days:

<iframe style="border-radius:12px" src="https://open.spotify.com/embed/playlist/4aanYfHYCGsV07TFTk4M3p?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>

This playlist, as the title sugguests, is a compilation of my favorite songs across all genres in one place:

<iframe style="border-radius:12px" src="https://open.spotify.com/embed/playlist/4lTVoR74tRM4i3q75AhDd6?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>

As much as I want everyone to believe that my curated playlists represent me, I realize that my "On Repeat" playlist generated by Spotify is a little bit more honest with my actual listening habits, so I will be vulnerable and share that here as well:

<iframe style="border-radius:12px" src="https://open.spotify.com/embed/playlist/37i9dQZF1EpAphfuDeFGkf?utm_source=generator&amp;theme=0" width="100%" height="352" frameBorder="0" allowfullscreen allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>

## Places I Have Been

Here is a map of places I have been to!

```{r}
#| label: Interactive Map
#| echo: false

library(readxl)
library(plotly)
library(tidyverse)

country_data <- read_excel("files/countries.xlsx")

Map <- plot_ly( 
  data = country_data,
  type = 'choropleth',     #using built in countries of the world map
  locations = ~Country,   #using countries as the location       
  locationmode = 'ISO-3',
  z = ~Visit,     #defining the variable for the map               
  text = ~Country,   #showing country name when hovered over
  colorscale = c("gray", "forestgreen"),  
  showscale = FALSE )

geo = list(
  showframe = FALSE,
  showcoastlines = FALSE,
  projection = list(type = 'equirectangular'),
  showcountries = TRUE,               
  countrycolor = "black",             
  countrywidth = 0.5                  
)


Map             
```  


